apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "k8s-sched.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-sched.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "k8s-sched.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.daemonSet.annotations | nindent 8 }}
      labels:
        {{- include "k8s-sched.selectorLabels" . | nindent 8 }}
    spec:
      hostPID: true
      serviceAccountName: {{ include "k8s-sched.serviceAccountName" . }}
      priorityClassName: {{ .Values.daemonSet.priorityClassName }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /agent
          args:
            - --node=$(NODE_NAME)
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: SCHED_BPF_OBJ
              value: {{ .Values.daemonSet.bpfObjectPath }}
            - name: HOST_PROC
              value: {{ .Values.daemonSet.hostProcPath }}
            - name: CGROUP_V2_ROOT
              value: {{ .Values.daemonSet.hostCgroupPath }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: cgroup
              mountPath: {{ .Values.daemonSet.hostCgroupPath }}
              readOnly: true
            - name: bpf-fs
              mountPath: /sys/fs/bpf
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: bpf-fs
          hostPath:
            path: /sys/fs/bpf
            type: DirectoryOrCreate
