{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "k8s-sched.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-sched.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: metrics
      interval: {{ .Values.serviceMonitor.interval }}
      path: {{ .Values.metrics.path }}
  selector:
    matchLabels:
      {{- include "k8s-sched.selectorLabels" . | nindent 6 }}
{{- end }}
